export const cartConstants = {
  CART_ADD_ITEM: 'CART_ITEM_ADD',
  CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
  CART_SAVE_SHIPPING_ADDRESS: 'CART_SAVE_SHIPPING_ADDRESS',
  CART_SAVE_PAYMENT_METHOD: 'CART_SAVE_PAYMENT_METHOD',
  CART_ITEMS_RESET: 'CART_ITEMS_RESET',
}
